from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any, Dict, List

from . import __version__
from .models import AssertionResult, SemanticModel
from .utils import get_git_info


def generate_report(
    results: List[AssertionResult],
    model: SemanticModel,
    config: Dict[str, Any],
    output_path: Path,
) -> Path:
    """Generates an audit report file in Markdown (.md), HTML (.html), or JSON (.json)."""
    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    suffix = output_path.suffix.lower()

    if suffix == ".json":
        _generate_json_report(results, model, config, output_path)
    elif suffix == ".html":
        _generate_html_report(results, model, config, output_path)
    else:
        _generate_markdown_report(results, model, config, output_path)

    return output_path


def _generate_markdown_report(
    results: List[AssertionResult],
    model: SemanticModel,
    config: Dict[str, Any],
    output_path: Path,
) -> None:
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    git_info = get_git_info(output_path)
    total = len(results)
    passed = sum(1 for r in results if r.passed)
    failed = total - passed
    status_label = "✅ PASSED" if failed == 0 else "❌ FAILED"

    lines = [
        "# Power BI Semantic Model Contract & Governance Audit Report",
        "",
        f"> **Generated by:** `pbi-guard v{__version__}`  ",
        f"> **Timestamp:** {now_utc}  ",
        f"> **Git Reference:** `{git_info['commit']}` (Branch: `{git_info['branch']}`)  ",
        f"> **Overall Verdict:** **{status_label}** ({passed}/{total} Passed)",
        "",
        "---",
        "",
        "## 1. Stakeholder Acceptance & UAT Sign-Off",
        "",
        "This document certifies that automated contract assertions, calculation integrity tests, and architectural standards were executed against this semantic model prior to deployment.",
        "",
        "| Role | Stakeholder Name | Signature | Status | Date |",
        "| :--- | :--- | :--- | :---: | :--- |",
        "| **BI / Analytics Engineer** | ____________________ | ____________________ | [ ] Approved [ ] Rejected | ________ |",
        "| **Business Domain Owner (UAT)** | ____________________ | ____________________ | [ ] Approved [ ] Rejected | ________ |",
        "| **Data Governance Lead** | ____________________ | ____________________ | [ ] Approved [ ] Rejected | ________ |",
        "",
        "---",
        "",
        "## 2. Assertion Audit Log",
        "",
        "| Status | Assertion Name | Type | Target / Scope | Details |",
        "| :---: | :--- | :--- | :--- | :--- |",
    ]

    for r in results:
        status_icon = "❌ FAIL" if (not r.passed or r.is_error) else "✅ PASS"
        rule_type = f"`{r.rule_type or 'custom'}`"
        target = f"`{r.target}`" if r.target else "*Global*"
        details = (r.reason or r.actual or "All contracts met").replace("\n", "<br>").replace("|", "\\|")
        lines.append(f"| {status_icon} | **{r.name}** | {rule_type} | {target} | {details} |")

    calc_col_total = sum(len(cols) for cols in model.calculated_columns.values())
    lines.extend([
        "",
        "---",
        "",
        "## 3. Semantic Model Architecture Inventory",
        "",
        f"- **Tables ({len(model.tables)}):** {', '.join(f'`{t}`' for t in sorted(model.tables)) or 'None'}",
        f"- **Total Business Measures:** {len(model.measures)} defined",
        f"- **Fact-Table Calculated Columns:** {calc_col_total} " + ("*(Clean)*" if calc_col_total == 0 else "⚠️ *(Requires Architectural Review)*"),
        "",
        "_Report automatically generated via `pbi-guard` contract runner._",
    ])

    output_path.write_text("\n".join(lines), encoding="utf-8")


def _generate_html_report(
    results: List[AssertionResult],
    model: SemanticModel,
    config: Dict[str, Any],
    output_path: Path,
) -> None:
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    git_info = get_git_info(output_path)
    total = len(results)
    passed = sum(1 for r in results if r.passed)
    failed = total - passed
    status_label = "PASSED" if failed == 0 else "FAILED"
    status_color = "#16a34a" if failed == 0 else "#dc2626"

    rows = []
    for r in results:
        is_pass = r.passed and not r.is_error
        badge = (
            '<span style="background:#dcfce7;color:#166534;padding:2px 8px;border-radius:4px;font-weight:600;">PASS</span>'
            if is_pass
            else '<span style="background:#fee2e2;color:#991b1b;padding:2px 8px;border-radius:4px;font-weight:600;">FAIL</span>'
        )
        details = (r.reason or r.actual or "All contracts satisfied").replace("<", "&lt;").replace(">", "&gt;")
        rows.append(f"""
        <tr>
            <td style="text-align:center;">{badge}</td>
            <td><strong>{r.name}</strong></td>
            <td><code>{r.rule_type or 'custom'}</code></td>
            <td><code>{r.target or 'Global'}</code></td>
            <td style="font-family:monospace;font-size:0.85em;color:#334155;">{details}</td>
        </tr>
        """)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Power BI Governance Audit Report</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 40px auto; max-width: 1000px; color: #0f172a; line-height: 1.5; }}
        h1, h2 {{ border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }}
        .header-box {{ background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 8px; padding: 20px; margin-bottom: 30px; }}
        .badge {{ font-size: 1.1em; font-weight: bold; color: {status_color}; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 0.9em; }}
        th, td {{ border: 1px solid #cbd5e1; padding: 10px 12px; text-align: left; vertical-align: top; }}
        th {{ background: #f1f5f9; }}
        .sign-table td {{ height: 45px; }}
    </style>
</head>
<body>
    <h1>Power BI Semantic Model Audit & UAT Report</h1>
    <div class="header-box">
        <div><strong>Overall Verdict:</strong> <span class="badge">{status_label}</span> ({passed}/{total} Passed)</div>
        <div><strong>Engine:</strong> pbi-guard v{__version__} | <strong>Timestamp:</strong> {now_utc}</div>
        <div><strong>Git SHA:</strong> <code>{git_info['commit']}</code> (Branch: <code>{git_info['branch']}</code>)</div>
    </div>

    <h2>1. Formal Stakeholder UAT Sign-Off</h2>
    <table class="sign-table">
        <tr><th>Role</th><th>Stakeholder Name</th><th>Signature</th><th>Decision</th><th>Date</th></tr>
        <tr><td><strong>Lead Analytics Engineer</strong></td><td></td><td></td><td>[ ] Approved [ ] Rejected</td><td></td></tr>
        <tr><td><strong>Business Domain Owner</strong></td><td></td><td></td><td>[ ] Approved [ ] Rejected</td><td></td></tr>
        <tr><td><strong>Governance Officer</strong></td><td></td><td></td><td>[ ] Approved [ ] Rejected</td><td></td></tr>
    </table>

    <h2>2. Assertion Results Log</h2>
    <table>
        <tr><th>Status</th><th>Assertion</th><th>Type</th><th>Target</th><th>Details</th></tr>
        {''.join(rows)}
    </table>

    <h2>3. Architecture Summary</h2>
    <p><strong>Tables ({len(model.tables)}):</strong> {', '.join(sorted(model.tables))}</p>
    <p><strong>Total Measures:</strong> {len(model.measures)}</p>
    <p><strong>Calculated Columns:</strong> {sum(len(c) for c in model.calculated_columns.values())}</p>
</body>
</html>
"""
    output_path.write_text(html, encoding="utf-8")


def _generate_json_report(
    results: List[AssertionResult],
    model: SemanticModel,
    config: Dict[str, Any],
    output_path: Path,
) -> None:
    git_info = get_git_info(output_path)
    data = {
        "generator": f"pbi-guard v{__version__}",
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "git": git_info,
        "summary": {
            "total": len(results),
            "passed": sum(1 for r in results if r.passed),
            "failed": sum(1 for r in results if not r.passed),
            "errors": sum(1 for r in results if r.is_error),
            "verdict": "PASSED" if all(r.passed for r in results) else "FAILED",
        },
        "inventory": {
            "tables_count": len(model.tables),
            "tables": sorted(model.tables),
            "measures_count": len(model.measures),
            "calculated_columns_count": sum(len(c) for c in model.calculated_columns.values()),
        },
        "results": [
            {
                "name": r.name,
                "rule_type": r.rule_type,
                "target": r.target,
                "passed": r.passed,
                "expected": r.expected,
                "actual": r.actual,
                "reason": r.reason,
                "is_error": r.is_error,
            }
            for r in results
        ],
    }
    output_path.write_text(json.dumps(data, indent=2), encoding="utf-8")